# Dockerfile.streamlit

FROM python:3.9-slim

WORKDIR /app

COPY streamlit_app.py /app

RUN pip install streamlit requests

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
