# Dockerfile.flask

FROM python:3.9-slim

WORKDIR /app

COPY flask_app.py /app
RUN mkdir /app/Meta-Llama-3-8B

RUN pip install --no-cache-dir Flask transformers torch

EXPOSE 5000

CMD ["python", "flask_app.py"]
